name: torch
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8.10
  - pip
  - cudatoolkit=11.6
  - pytorch=1.13.1
  - torchvision=0.14.1
  - torchaudio==0.13.1
  - numpy=1.22.3
  - pip:
    - albumentations==1.1.0
    - opencv-python==4.2.0.34
    - pudb==2019.2
    - imageio==2.14.1
    - imageio-ffmpeg==0.4.7
    - pytorch-lightning==1.5.9
    - omegaconf==2.1.1
    - test-tube>=0.7.5
    - streamlit>=0.73.1
    - setuptools==59.5.0
    - pillow==9.0.1
    - einops==0.4.1
    - torch-fidelity
    - torchmetrics
    - kornia==0.6
    - accelerate>=0.16.0
    - transformers>=4.25.1
    - datasets
    - ftfy
    - tensorboard
    - Jinja2
    - peft==0.7.0
    - pandas
    - matplotlib
    - scikit-learn
    - nibabel
    - monai 
    - -e git+https://github.com/CompVis/taming-transformers.git@master#egg=taming-transformers
    - -e git+https://github.com/openai/CLIP.git@main#egg=clip
    - git+https://github.com/Project-MONAI/MONAI.git#egg=monai[nibabel,skimage]
    - git+https://github.com/huggingface/diffusers.git
    - simpleitk
    - yacs